apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin
  namespace: observability
type: Opaque
stringData:
  admin-user: admin
  # Cambiar en producción.
  admin-password: "grafana_admin_password_123"
